# Generated by Django 3.2.22 on 2023-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePointName', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('rko', models.BooleanField()),
                ('officeType', models.BooleanField()),
                ('officeTypeAdditional', models.CharField(max_length=256)),
                ('salePointFormat', models.CharField(max_length=256)),
                ('suoAvailability', models.BooleanField()),
                ('hasRamp', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('kep', models.FloatField()),
                ('myBranch', models.FloatField()),
            ],
        ),
    ]
