# Generated by Django 3.2.22 on 2023-10-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='officeTypeAdditional',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
