# Generated by Django 3.2.22 on 2023-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_alter_office_officetypeadditional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kep',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='myBranch',
            field=models.BooleanField(),
        ),
    ]
