# Generated by Django 3.2.22 on 2023-10-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20231014_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=2)),
                ('hour', models.CharField(max_length=5)),
                ('percentage', models.IntegerField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.office')),
            ],
        ),
    ]
